server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-medico
              uri: http://ms-medico:8081
              predicates:
                - Path=/api/medicos/**

            - id: ms-especialidade
              uri: http://ms-medico:8081
              predicates:
                - Path=/api/especialidades/**

            - id: ms-paciente
              uri: http://ms-paciente:8082
              predicates:
                - Path=/api/pacientes/**

            - id: ms-convenio
              uri: http://ms-paciente:8082
              predicates:
                - Path=/api/convenios/**

            - id: ms-agenda
              uri: http://ms-agenda:8083
              predicates:
                - Path=/api/agendas/**

            - id: ms-auth
              uri: http://ms-auth:8084
              predicates:
                - Path=/api/auth/**
jwt:
  secret: mySecretKeyForJWTGenerationThatIsAtLeast32BytesLong
  public-paths:
    - /api/auth/login
    - /api/auth/register
    - /actuator/health