server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-medico
              uri: http://localhost:8081
              predicates:
                - Path=/api/medicos/**

            - id: ms-especialidade
              uri: http://localhost:8081
              predicates:
                - Path=/api/especialidades/**

            - id: ms-paciente
              uri: http://localhost:8082
              predicates:
                - Path=/api/pacientes/**

            - id: ms-convenio
              uri: http://localhost:8082
              predicates:
                - Path=/api/convenios/**

            - id: ms-auth
              uri: http://localhost:8084
              predicates:
                - Path=/api/auth/**
jwt:
  secret: mySecretKeyForJWTGenerationThatIsAtLeast32BytesLong
  public-paths:
    - /api/auth/login
    - /api/auth/register
    - /actuator/health