version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # porta de comunicação do broker
      - "15672:15672"     # painel web do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ms-medico:
    build:
      context: ./ms-medico
    container_name: ms-medico
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  ms-paciente:
    build:
      context: ./ms-paciente
    container_name: ms-paciente
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  ms-agenda:
    build:
      context: ./ms-agenda
    container_name: ms-agenda
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres
      - rabbitmq
      - ms-medico
      - ms-paciente

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: agendamento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data